// Code generated by mockery v2.53.4. DO NOT EDIT.

package gcp

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockService) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteService provides a mock function with given fields: ctx, serviceName
func (_m *MockService) DeleteService(ctx context.Context, serviceName string) error {
	ret := _m.Called(ctx, serviceName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, serviceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeployService provides a mock function with given fields: ctx, projectID, imageName, serviceName
func (_m *MockService) DeployService(ctx context.Context, projectID string, imageName string, serviceName string) (string, error) {
	ret := _m.Called(ctx, projectID, imageName, serviceName)

	if len(ret) == 0 {
		panic("no return value specified for DeployService")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, projectID, imageName, serviceName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, projectID, imageName, serviceName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, projectID, imageName, serviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBuildLogs provides a mock function with given fields: ctx, buildID
func (_m *MockService) GetBuildLogs(ctx context.Context, buildID string) (string, error) {
	ret := _m.Called(ctx, buildID)

	if len(ret) == 0 {
		panic("no return value specified for GetBuildLogs")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, buildID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, buildID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, buildID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListServices provides a mock function with given fields: ctx
func (_m *MockService) ListServices(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListServices")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TriggerBuild provides a mock function with given fields: ctx, karadaProjectID, gcsSourceURI, imageName, onStart
func (_m *MockService) TriggerBuild(ctx context.Context, karadaProjectID string, gcsSourceURI string, imageName string, onStart func(string, string)) (string, string, string, error) {
	ret := _m.Called(ctx, karadaProjectID, gcsSourceURI, imageName, onStart)

	if len(ret) == 0 {
		panic("no return value specified for TriggerBuild")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, func(string, string)) (string, string, string, error)); ok {
		return rf(ctx, karadaProjectID, gcsSourceURI, imageName, onStart)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, func(string, string)) string); ok {
		r0 = rf(ctx, karadaProjectID, gcsSourceURI, imageName, onStart)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, func(string, string)) string); ok {
		r1 = rf(ctx, karadaProjectID, gcsSourceURI, imageName, onStart)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, func(string, string)) string); ok {
		r2 = rf(ctx, karadaProjectID, gcsSourceURI, imageName, onStart)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string, string, func(string, string)) error); ok {
		r3 = rf(ctx, karadaProjectID, gcsSourceURI, imageName, onStart)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// UploadSource provides a mock function with given fields: ctx, projectID, zipContent
func (_m *MockService) UploadSource(ctx context.Context, projectID string, zipContent []byte) (string, error) {
	ret := _m.Called(ctx, projectID, zipContent)

	if len(ret) == 0 {
		panic("no return value specified for UploadSource")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return rf(ctx, projectID, zipContent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = rf(ctx, projectID, zipContent)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, projectID, zipContent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
